### ISSUE TITLE
老哥求一份群辉nas上的docker的配置流程

### ISSUE THREAD

**Issue by wache8787** [aaro-n/cf2dns-docker#1]
老哥求一份群辉nas上的docker的配置流程
镜像已经安装好了，但是不知道怎么配置。。

不忙了看看能不能出一份群辉nas上的docker的配置流程。感激不尽！

**Comment by aaro-n** [comment]
没有群晖nas，你可以去找找群晖运行docker教程。

**Comment by wache8787** [comment]
联系QQ 2333373https://www.meitong.pro/用手机自带浏览器，感谢支持。
